# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        files: \.py$

    -   id: end-of-file-fixer
        files: \.py$

    -   id: check-yaml

    -   id: check-added-large-files

    -   id: check-merge-conflict

    -   id: check-toml

-   repo: local 
    hooks:
    -   id: black
        language: system
        name: run black
        files: \.py$
        entry: python -m black -S --skip-string-normalization

    -   id: isort
        language: system
        name: run isort
        files: \.py$
        entry: python -m isort --profile black

    -   id: velin
        language: system
        name: run velin
        files: \.py$
        entry: python -m velin --write

